# Generated by Django 4.0.2 on 2022-02-11 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название принтера', max_length=100, verbose_name='Имя')),
                ('api_key', models.CharField(help_text='ключ доступа к API', max_length=100, unique=True, verbose_name='Ключ')),
                ('check_type', models.CharField(choices=[('kitchen', 'Kitchen'), ('client', 'Client')], help_text='тип чека которые печатает принтер', max_length=100, verbose_name='Тип')),
                ('point_id', models.IntegerField(help_text='точка к которой привязан принтер', max_length=100, verbose_name='ID точки')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kitchen', 'Kitchen'), ('client', 'Client')], max_length=50, verbose_name='Тип')),
                ('order', models.JSONField(help_text='Информация о заказе', verbose_name='Инфо')),
                ('status', models.CharField(choices=[('new', 'New'), ('rendered', 'Rendered'), ('printed', 'Printed')], help_text='Статус чека', max_length=50, verbose_name='Статус')),
                ('pdf_file', models.FileField(help_text='ссылка на созданный PDF-файл', upload_to='', verbose_name='Ссылка')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='check_printer.printer', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
    ]
