# Generated by Django 4.0.2 on 2022-02-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_printer', '0002_alter_printer_point_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='order',
            field=models.JSONField(help_text='Информация о заказе', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('rendered', 'Rendered'), ('printed', 'Printed')], default='new', help_text='Статус чека', max_length=50, verbose_name='Статус'),
        ),
    ]
