# Generated by Django 4.0.2 on 2022-02-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_printer', '0003_alter_check_order_alter_check_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='ссылка на созданный PDF-файл', null=True, upload_to='', verbose_name='Ссылка'),
        ),
    ]
