version: '3.7'

services:
  pdf_generator:
    container_name: pdf_generator
    image: openlabs/docker-wkhtmltopdf-aas:latest
    volumes:
      - ./app/media:/data
    ports:
      - "7500:7500"
    networks:
      - for_far
  redis:
    restart: unless-stopped
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - for_far
  db:
    image: postgres
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
#      - ./compose/postgres/initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - for_far


  app:
    build:
      context: ./app
      dockerfile: app/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/
    networks:
      - for_far
    depends_on:
      - pdf_generator
      - redid
      - db



networks:
  for_far:
    driver: bridge