version: '3.7'

services:
  pdf_gen:
    image: wkhtmltopdf


  redis:
    restart: unless-stopped
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - for_far
  db:
    image: postgres
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
#      - ./compose/postgres/initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - for_far


  app:
    build:
      context: ./web
      dockerfile: web/Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./web:/app/
    networks:
      - for_far
    depends_on:
      - redid
      - db


volumes:
  static_volume:
  media_volume:

networks:
  for_far:
    driver: bridge