version: '3.7'

services:
  pdf_gen:
    container_name: pdf_gen
    image: openlabs/docker-wkhtmltopdf-aas:latest
    volumes:
      - ./app/media:/data
    ports:
      - "7500:7500"
    networks:
      - for_far
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - for_far
#  db:
#    image: postgres
#    container_name: postgres_db
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
##      - ./compose/postgres/initdb:/docker-entrypoint-initdb.d
#    environment:
#      - POSTGRES_NAME=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#
#    restart: unless-stopped
#    ports:
#      - "5432:5432"
#    networks:
#      - for_far


  app:
    build:
      context: ./app
      dockerfile: app/Dockerfile
    command: "poetry run python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/
    networks:
      - for_far
    depends_on:
      - pdf_gen
      - redis
#      - db

  rq_worker:
    container_name: rq_worker
    build: ./app
    command:b


networks:
  for_far:
    driver: bridge