version: '3.7'

services:

  redis:
    hostname: ff_redis
    container_name: ff_redis
    restart: unless-stopped
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - for_far
#  db:
#    image: postgres
#    container_name: postgres_db
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
##      - ./compose/postgres/initdb:/docker-entrypoint-initdb.d
#    environment:
#      - POSTGRES_NAME=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#
#    restart: unless-stopped
#    ports:
#      - "5432:5432"
#    networks:
#      - for_far


  app:
    hostname: ff_app
    container_name: ff_app
    build:
      context: .
      dockerfile: app/Dockerfile
    command: poetry run python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/
    networks:
      - for_far
    depends_on:
      - redis
#      - db

  rq_worker:
    hostname: ff_rq_worker
    container_name: ff_worker
    build:
      context: .
      dockerfile: app/Dockerfile
    command: poetry run python manage.py rqworker default
    env_file:
      - .env.dev
    volumes:
      - ./app:/app/
    networks:
      - for_far
    depends_on:
      - redis
      - app

networks:
  for_far:
    driver: bridge
